# AI-generated by Claude Code (claude-opus-5) — 20260731
# Task: positional ranging of EPM seqlets with config-driven window geometry and a symmetric TSS/TTS frame
# Reviewed by:
#
# Differences from the previous implementation, all deliberate:
#   1. Window geometry (upstream_len / body_len / spacer) comes from config instead of the hardcoded
#      1500 / 1520 / 3020, so non-vanilla deepCRE and phytoExpr setups can be ranged correctly.
#   2. The TTS half is flipped with (sequence_length + 1) - start, not sequence_length - start. The old
#      formula put the TTS border at position 1000 while the TSS border sat at 1001, i.e. the two halves
#      disagreed by 1 bp about where the gene begins.
#   3. The TTS range bound is [upstream+body+spacer+1, sequence_length] = [1521, 3020], not the old
#      [1520, 3000], which had included one spacer base and discarded the 20 most distal downstream bases
#      while the TSS half used its full 1500.
#   4. `mode` is binned after the flip so it lives in the same frame as every other column.
#   5. `cv` is NaN-guarded (sd is undefined for single-seqlet patterns).
#   6. Writes <spec><model>-ranging_geometry.json so the annotation step can verify, rather than assume,
#      the frame these thresholds are expressed in.
import json
import os

import h5py
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from tqdm import tqdm

SEQLET_RE = r'example:(\d+),start:(\d+),end:(\d+),rc:(\w+)'


def resolve_geometry(common_settings, config):
    """Window geometry of the model input. Defaults are deepCRE vanilla."""
    w = dict(common_settings.get('window') or {})
    upstream = int(w.get('upstream_len', 1000))
    body = int(w.get('body_len', 500))
    spacer = int(w.get('spacer', 20))
    seq_len = int(w.get('sequence_length', 2 * (upstream + body) + spacer))

    expected = 2 * (upstream + body) + spacer
    if seq_len != expected:
        raise ValueError(
            f"window geometry inconsistent: 2*(upstream_len {upstream} + body_len {body}) + spacer "
            f"{spacer} = {expected}, but sequence_length is {seq_len}. Fix the config."
        )

    geom = {
        'upstream_len': upstream,
        'body_len': body,
        'spacer': spacer,
        'sequence_length': seq_len,
        # unified frame shared by both halves: 1 = outer flank edge, border_pos = first/last transcript
        # base, up to half_len = body_len into the transcript
        'half_len': upstream + body,
        'border_pos': upstream + 1,
        'tss_range': [1, upstream + body],
        'tts_range': [upstream + body + spacer + 1, seq_len],
        'tts_flip': 'start -> (sequence_length + 1) - start',
        'frame': 'unified: 1 = outer flank edge, border_pos = gene border, half_len = body_len into transcript',
    }
    return geom


def _custom_mode(series, bin_width=10):
    s = series.dropna()
    if s.empty:
        return np.nan
    binned = (s // bin_width).mode()
    return float(binned.iloc[0] * bin_width) if not binned.empty else np.nan


def _stats(df, source_file, species, model, region):
    if df.empty:
        return pd.DataFrame()
    g = df.groupby('motif')['start']
    out = pd.DataFrame({
        'min': g.min(), 'max': g.max(),
        'q10': g.quantile(0.1), 'median': g.median(), 'q90': g.quantile(0.9),
        'mean': g.mean(), 'sd': g.std(), 'number': g.count(),
    })
    out['mode'] = df.groupby('motif')['start'].apply(_custom_mode)
    # sd is undefined for a single observation; do not let that become inf/garbage
    out['cv'] = np.where(
        out['mean'].to_numpy() > 0,
        out['sd'].to_numpy() / out['mean'].to_numpy() * 100.0,
        np.nan,
    )
    out['iqr'] = out['q90'] - out['q10']
    out = out.reset_index()
    out['epm'] = f"epm_{species}_{model}_" + out['motif']
    out['region'] = region
    out['source'] = os.path.basename(source_file)
    cols = ['epm', 'min', 'max', 'mean', 'median', 'mode', 'q10', 'q90',
            'sd', 'cv', 'iqr', 'number', 'region', 'source']
    return out[cols]


def _motif_id(row):
    try:
        n = str(row['pattern'])[8:]
        if not n:
            return None
        prefix = 'p0' if row['metacluster'] == 'metacluster_0' else 'p1'
        return f"{prefix}m{int(n):02d}"
    except (ValueError, TypeError, IndexError):
        return None


def run(config, common_settings):
    hdf5 = common_settings.get('input_hdf5')
    output_dir = config['output_dir']
    if not hdf5 or not os.path.exists(hdf5):
        print(f"Error: input HDF5 not found at '{hdf5}'. Skipping ranging.")
        return

    species = common_settings.get('species_tag', 'unk')
    model = common_settings.get('model_tag', 'm0')
    geom = resolve_geometry(common_settings, config)
    print(f"Window geometry: upstream={geom['upstream_len']} body={geom['body_len']} "
          f"spacer={geom['spacer']} sequence_length={geom['sequence_length']}")
    print(f"  TSS half {geom['tss_range']}, TTS half {geom['tts_range']} flipped by "
          f"({geom['sequence_length']} + 1) - start; gene border at {geom['border_pos']} in both halves")

    rows = []
    with h5py.File(hdf5, 'r') as h5:
        group = h5.get('metacluster_idx_to_submetacluster_results')
        if group is None:
            print("Error: 'metacluster_idx_to_submetacluster_results' not in HDF5.")
            return
        for mc_name, mc in tqdm(group.items(), desc="Extracting seqlets"):
            patterns = mc['seqlets_to_patterns_result']['patterns']
            for p_name, p in patterns.items():
                if not p_name.startswith('pattern_'):
                    continue
                for raw in p['seqlets_and_alnmts']['seqlets'][:]:
                    rows.append({'seqlets': raw.decode('utf-8'), 'pattern': p_name, 'metacluster': mc_name})

    if not rows:
        print("Warning: no seqlets found. Skipping ranging.")
        return

    data = pd.DataFrame(rows)
    ext = data['seqlets'].str.extract(SEQLET_RE)
    ext.columns = ['example', 'start', 'end', 'rc']
    data = pd.concat([data[['pattern', 'metacluster']], ext], axis=1)
    data['motif'] = data.apply(_motif_id, axis=1)
    data.dropna(subset=['motif', 'start', 'end'], inplace=True)
    data['start'] = pd.to_numeric(data['start'])
    data['end'] = pd.to_numeric(data['end'])
    # `rc` is a motif-strand attribute, not a coordinate: MoDISco `start` is always in the forward frame
    # of the gene-oriented deepCRE window, so pooling across rc is correct for positional statistics.

    seq_len, half = geom['sequence_length'], geom['half_len']
    tss_lo, tss_hi = geom['tss_range']
    tts_lo, tts_hi = geom['tts_range']

    r1 = data[(data['start'] >= tss_lo) & (data['end'] <= tss_hi)].copy()
    r2 = data[(data['start'] >= tts_lo) & (data['end'] <= tts_hi)].copy()
    dropped = len(data) - len(r1) - len(r2)
    print(f"Seqlets: {len(data):,} total -> TSS half {len(r1):,}, TTS half {len(r2):,}, "
          f"spanning a boundary and dropped {dropped:,}")

    r2['start'] = (seq_len + 1) - r2['start']

    res1 = _stats(r1, hdf5, species, model, 'upstream')
    res2 = _stats(r2, hdf5, species, model, 'downstream')

    if config.get('generate_plots', True):
        plot_dir = os.path.join(output_dir, 'distribution_plots')
        os.makedirs(plot_dir, exist_ok=True)
        for region, df in (('TSS', r1), ('TTS', r2)):
            for motif_id, grp in df.groupby('motif'):
                plt.figure(figsize=(10, 2.5))
                sns.kdeplot(grp['start'], color='darkcyan', fill=True)
                plt.axvline(geom['border_pos'], color='k', ls='--', lw=1)
                plt.title(f"{region} positional density - epm_{species}_{model}_{motif_id}")
                plt.xlabel(f"unified frame (1 = flank edge, {geom['border_pos']} = gene border, {half} = body)")
                plt.xlim(0, half)
                plt.savefig(os.path.join(plot_dir, f"epm_{species}_{model}_{motif_id}_{region}_density.png"),
                            dpi=150, bbox_inches='tight')
                plt.close()

    for res, tag in ((res1, 'TSS'), (res2, 'TTS')):
        if res.empty:
            print(f"Warning: no {tag} statistics produced.")
            continue
        path = os.path.join(output_dir, f"{species}{model}-{tag}_motif_ranges.csv")
        res.to_csv(path, index=False, float_format='%.3f')
        thin = int((res['number'] < 20).sum())
        print(f"{tag}: {len(res)} EPMs -> {path}"
              f"   (bands resting on <20 seqlets: {thin})")

    geom_path = os.path.join(output_dir, f"{species}{model}-ranging_geometry.json")
    with open(geom_path, 'w') as f:
        json.dump(geom, f, indent=2)
    print(f"Frame metadata -> {geom_path}")
    print("Ranging step successfully completed.")
