# AI-generated by Claude Code (claude-opus-5) — 20260731
# Task: annotate BLAMM EPM occurrences to genes and apply per-EPM positional filters in the ranging frame
# Reviewed by:
#
# The defect this fixes:
#   The previous implementation compared `dist_transc_border` -- a distance measured OUTWARD from the gene border,
#   domain [0, flank] -- against q10/q90, which ranging expresses in a frame where the gene border sits at
#   ~1000 and the preferred range typically runs 1000-1490, i.e. INSIDE the transcript. The two frames are
#   mirrored and offset. Measured consequence over six runs: q10 exceeded the flank width for 20-36 of
#   every ~50 EPMs per region, so 45-60 of ~58-111 EPM x region pairs retained exactly zero hits, while
#   88-97% of all hits (everything classified intragenic) bypassed the filter entirely.
#
# This version puts each hit INTO the ranging frame instead of converting thresholds, which is both simpler
# and robust to chromosome-edge truncation of the extracted region (w depends only on the gene coordinates
# and the motif's genomic position, never on the region's left edge).
#
# Also restored from the moca_blue reference (mo_proj/mo_feat-filter.v3.x), all config-gated:
#   - nearest-border assignment, so no hit is assigned to both borders in a short gene
#   - the in-scope pre-filter, applied per chunk before the GFF merge
#   - deduplication, which collapses the exact 2x F/R redundancy (nomenclature emits both strand
#     matrices and step8 scans with -rc, so every instance is reported twice)
#   - weight_region, the abundance / degenerate-band gate
# Dropped deliberately: the legacy `word_size` gate. BLAMM emits exactly one span per EPM variant
# (verified: 0 of 100 Cqui and 0 of 112 Hvul EPMs show more than one), so it never removed partial
# matches; its real effect was rejecting border-straddling hits, which nearest-border now handles.
import glob
import json
import os

import numpy as np
import pandas as pd
from tqdm import tqdm

OCC_COLS = ['loc', 'source', 'epm_instance', 'mstart', 'mend', 'score', 'strand', 'pval', 'seq']


def _std_chr(series):
    return series.astype(str).str.lower().str.replace('^chr', '', regex=True)


def _load_gff(filepath):
    cols = ['seqid', 'source', 'type', 'start', 'end', 'score', 'strand', 'phase', 'attributes']
    df = pd.read_csv(filepath, sep='\t', comment='#', header=None, names=cols, low_memory=False)
    gene_id = None
    for pattern in (r'gene_id\s*"([^"]+)"', r'gene_id=([^;]+)', r'ID=([^;]+)', r'Parent=gene:([^;]+)'):
        gene_id = df['attributes'].str.extract(pattern, expand=False)
        if not gene_id.isnull().all():
            break
    if gene_id is None or gene_id.isnull().all():
        raise ValueError(f"Could not extract any gene identifier from {filepath}")
    df['gene_id'] = gene_id.fillna('N/A')
    return df


def _load_geometry(ranging_dir, species, model, common_settings):
    path = os.path.join(ranging_dir, f"{species}{model}-ranging_geometry.json")
    if os.path.exists(path):
        with open(path) as f:
            geom = json.load(f)
        print(f"Ranging frame read from {os.path.basename(path)}")
        return geom
    w = dict(common_settings.get('window') or {})
    up, body, spacer = int(w.get('upstream_len', 1000)), int(w.get('body_len', 500)), int(w.get('spacer', 20))
    print("WARNING: no ranging_geometry.json alongside the range files. Falling back to the config window "
          f"(upstream={up}, body={body}, spacer={spacer}). If those range files came from the old "
          "step7_ranging.py, their TTS half is offset by 1 bp and truncated by 20 bp -- re-run ranging.")
    return {'upstream_len': up, 'body_len': body, 'spacer': spacer,
            'sequence_length': 2 * (up + body) + spacer, 'half_len': up + body, 'border_pos': up + 1}


def _load_ranges(ranging_dir, species, model):
    frames = []
    for tag, region in (('TSS', 'upstream'), ('TTS', 'downstream')):
        path = os.path.join(ranging_dir, f"{species}{model}-{tag}_motif_ranges.csv")
        t = pd.read_csv(path)
        t['region'] = region
        frames.append(t)
    t = pd.concat(frames, ignore_index=True)
    t['region_fraction'] = t['number'] / t.groupby('epm')['number'].transform('sum')
    return t


def _write(df, output_dir, name, report_key=None):
    if df.empty:
        print(f"Warning: nothing to write for '{name}'.")
        return
    cols = ['chr', 'gene_id', 'gene_start', 'gene_end', 'gene_strand', 'epm', 'epm_instance',
            'cwm_strand', 'gen_mstart', 'gen_mend', 'strand', 'score', 'region', 'w', 'dist_border']
    out = df[[c for c in cols if c in df.columns]]
    csv_path = os.path.join(output_dir, f"annotated_motifs_{name}.csv")
    out.to_csv(csv_path, index=False, float_format='%.3f')
    bed = pd.DataFrame({
        '#chrom': df['chr'],
        'chromStart': df['gen_mstart'].astype(int) - 1,   # BED is 0-based half-open
        'chromEnd': df['gen_mend'].astype(int),
        'name': df['epm_instance'],
        'score': df['score'],
        'strand': df['strand'],
    })
    bed.to_csv(os.path.join(output_dir, f"annotated_motifs_{name}.bed"), sep='\t', index=False)
    print(f"  {name}: {len(df):,} rows -> annotated_motifs_{name}.csv / .bed")


def run(config, common_settings):
    output_dir = config['output_dir']
    projection_dir = (common_settings.get('projection') or {}).get('output_dir')
    ranging_dir = (common_settings.get('ranging') or {}).get('output_dir')
    species = common_settings.get('species_tag', 'unk')
    model = common_settings.get('model_tag', 'm0')
    chunk_size = int(config.get('chunk_size', 500000))

    filters = config.get('filters') or {}
    band = str(filters.get('band', 'q1q9')).lower()
    if band not in ('none', 'minmax', 'q1q9'):
        raise ValueError(f"filters.band must be none|minmax|q1q9, got '{band}'")
    wr = filters.get('weight_region') or {}
    wr_enabled = bool(wr.get('enabled', True))
    min_fraction = float(wr.get('min_region_fraction', 0.15))
    min_seqlets = int(filters.get('min_region_seqlets', 20))
    deep_policy = str(config.get('deep_intragenic', 'drop')).lower()
    if deep_policy not in ('drop', 'pass'):
        raise ValueError(f"deep_intragenic must be drop|pass, got '{deep_policy}'")
    do_dedupe = bool(config.get('dedupe', True))
    min_match_rate = float((config.get('strict_merge') or {}).get('min_match_rate', 0.5))
    write_oos = bool(config.get('write_out_of_scope', False))

    geom = _load_geometry(ranging_dir, species, model, common_settings)
    up_len, body_len, half, border = (geom['upstream_len'], geom['body_len'],
                                      geom['half_len'], geom['border_pos'])
    flank = int((common_settings.get('projection') or {}).get('flank_size', 1000))
    if flank < up_len:
        raise ValueError(
            f"projection.flank_size ({flank}) is smaller than the model's upstream_len ({up_len}). "
            "The extracted sequence does not cover the region the EPM ranges are defined over; "
            "re-run projection with a larger flank."
        )
    if flank > up_len:
        print(f"Note: flank_size {flank} exceeds upstream_len {up_len}; the outer {flank - up_len} bp "
              "lie outside the model's field of view and will be reported as out of scope.")

    print(f"Frame: 1 = flank edge, {border} = gene border, {half} = {body_len} bp into the transcript")
    print(f"Filters: band={band}  weight_region={wr_enabled} (min_region_fraction={min_fraction}) "
          f"min_region_seqlets={min_seqlets}  deep_intragenic={deep_policy}  dedupe={do_dedupe}")

    gff = _load_gff(config['reference_gff'])
    genes = gff[gff['type'] == 'gene'].copy()
    genes.rename(columns={'seqid': 'chr', 'start': 'gene_start', 'end': 'gene_end',
                          'strand': 'gene_strand'}, inplace=True)
    # must reproduce step8 exactly, including its max(1, ...) clamp at chromosome starts
    genes['merge_key'] = (_std_chr(genes['chr']) + ':'
                          + np.maximum(1, genes['gene_start'] - flank).astype(str) + '-'
                          + (genes['gene_end'] + flank).astype(str))
    genes = genes[['merge_key', 'chr', 'gene_id', 'gene_start', 'gene_end', 'gene_strand']]
    print(f"GFF: {len(genes):,} genes")

    files = sorted(glob.glob(os.path.join(projection_dir, 'occurrences_part_*')))
    if not files:
        print(f"Error: no occurrences_part_* in {projection_dir}.")
        return

    stats = {'raw': 0, 'prefilter': 0, 'merged': 0, 'dedupe': 0, 'in_scope': 0,
             'deep_intragenic': 0, 'beyond_flank': 0}
    kept, oos = [], []
    reach = flank + body_len

    for path in files:
        print(f"--> {os.path.basename(path)}")
        for chunk in tqdm(pd.read_csv(path, sep='\t', header=None, names=OCC_COLS,
                                      chunksize=chunk_size, low_memory=False), desc="chunks"):
            if chunk.empty:
                continue
            stats['raw'] += len(chunk)

            parts = chunk['loc'].str.split(':', n=1, expand=True)
            if parts.shape[1] < 2:
                continue
            coord = parts[1].str.split('-', expand=True)
            r_lo = pd.to_numeric(coord[0], errors='coerce')
            r_hi = pd.to_numeric(coord[1], errors='coerce')
            # cheap pre-merge scope gate: a hit can only be in scope if it lies within
            # flank + body_len of one end of the extracted region. No gene coordinates needed.
            region_len = r_hi - r_lo + 1
            near = (chunk['mstart'] <= reach) | (chunk['mstart'] >= region_len - reach)
            chunk = chunk[near.fillna(False)].copy()
            if chunk.empty:
                continue
            chunk['r_lo'] = r_lo[chunk.index]
            chunk['merge_key'] = _std_chr(parts[0][chunk.index]) + ':' + parts[1][chunk.index]
            stats['prefilter'] += len(chunk)

            m = chunk.merge(genes, on='merge_key', how='inner')
            if m.empty:
                continue
            stats['merged'] += len(m)

            m['gen_mstart'] = m['r_lo'].astype(int) + m['mstart'].astype(int) - 1
            m['gen_mend'] = m['r_lo'].astype(int) + m['mend'].astype(int) - 1
            m['epm'] = m['epm_instance'].str.extract(r'(epm_.+?_p\d+m\d+)', expand=False)
            m['cwm_strand'] = m['epm_instance'].str.extract(r'p\d+m\d+([FR])', expand=False)
            m.dropna(subset=['epm'], inplace=True)
            if do_dedupe:
                # Order F before R so the survivor of each redundant pair is always the forward-CWM
                # match. Without this, which of the two is kept depends on BLAMM's output order, and
                # the surviving epm_instance / strand columns (and the BED name/strand fields) are
                # arbitrary -- observed as a 198,539 R vs 43,800 F split on AthaM0.
                m = (m.sort_values('cwm_strand', kind='stable')
                       .drop_duplicates(['gene_id', 'gen_mstart', 'gen_mend', 'epm']))
            stats['dedupe'] += len(m)

            plus = (m['gene_strand'] != '-').to_numpy()
            gs, ge, gm = (m['gene_start'].to_numpy(), m['gene_end'].to_numpy(), m['gen_mstart'].to_numpy())
            d_tss = np.where(plus, gs - gm, gm - ge)     # + = upstream of TSS, gene-oriented
            d_tts = np.where(plus, gm - ge, gs - gm)     # + = downstream of TTS, gene-oriented
            w_tss, w_tts = border - d_tss, border - d_tts
            in_tss = (w_tss >= 1) & (w_tss <= half)
            in_tts = (w_tts >= 1) & (w_tts <= half)
            # nearest border wins; a short gene never yields two rows for one hit
            pick_tss = in_tss & (~in_tts | (np.abs(d_tss) <= np.abs(d_tts)))
            pick_tts = in_tts & ~pick_tss

            m['region'] = np.select([pick_tss, pick_tts], ['upstream', 'downstream'], default='out_of_scope')
            m['w'] = np.select([pick_tss, pick_tts], [w_tss, w_tts], default=np.nan)
            m['dist_border'] = np.select([pick_tss, pick_tts], [d_tss, d_tts], default=np.nan)

            out_mask = m['region'].to_numpy() == 'out_of_scope'
            if out_mask.any():
                sub = m[out_mask].copy()
                inside = (sub['gen_mstart'] >= sub['gene_start']) & (sub['gen_mstart'] <= sub['gene_end'])
                sub['region'] = np.where(inside, 'deep_intragenic', 'beyond_flank')
                stats['deep_intragenic'] += int(inside.sum())
                stats['beyond_flank'] += int((~inside).sum())
                if write_oos or deep_policy == 'pass':
                    oos.append(sub)
            m = m[~out_mask]
            stats['in_scope'] += len(m)
            if not m.empty:
                kept.append(m)

    if stats['raw'] == 0:
        print("Error: occurrence files contained no rows.")
        return
    match_rate = stats['merged'] / max(stats['prefilter'], 1)
    print(f"\nGFF match rate on pre-filtered hits: {match_rate:.3f}")
    if match_rate < min_match_rate:
        raise ValueError(
            f"Only {match_rate:.1%} of in-range occurrences matched a gene key built from "
            f"{config['reference_gff']} at flank_size={flank}. This almost always means the occurrence "
            f"files were produced against a different annotation build. Aborting rather than annotating a "
            f"fraction of the data (threshold: strict_merge.min_match_rate={min_match_rate})."
        )

    if not kept:
        print("Warning: no in-scope hits after annotation.")
        return
    df = pd.concat(kept, ignore_index=True)
    if do_dedupe:   # chunk boundaries can split a duplicate pair
        before = len(df)
        df = (df.sort_values('cwm_strand', kind='stable')
                .drop_duplicates(['gene_id', 'gen_mstart', 'gen_mend', 'epm']))
        if before != len(df):
            print(f"Cross-chunk dedupe removed a further {before - len(df):,} rows")

    ranges = _load_ranges(ranging_dir, species, model)
    n_band = len(ranges)
    excluded = pd.Series(False, index=ranges.index)
    if wr_enabled:
        excluded |= ranges['region_fraction'] < min_fraction
    excluded |= ranges['number'] < min_seqlets
    dropped_bands = ranges[excluded]
    ranges = ranges[~excluded]
    print(f"\nBand admission: {len(ranges)}/{n_band} EPM x region retained "
          f"(weight_region + min_region_seqlets dropped {len(dropped_bands)})")
    if len(dropped_bands):
        thin = dropped_bands[dropped_bands['number'] < min_seqlets]
        print(f"  of those, {len(thin)} rested on fewer than {min_seqlets} seqlets "
              f"(narrowest band {dropped_bands['iqr'].min():.0f} bp)")
    if ranges.empty:
        raise ValueError("Every EPM x region was excluded. Loosen weight_region / min_region_seqlets.")

    keep_cols = ['epm', 'region', 'min', 'max', 'q10', 'q90', 'number', 'region_fraction', 'iqr']
    df = df.merge(ranges[keep_cols], on=['epm', 'region'], how='inner')
    stats['band_admitted'] = len(df)

    if band == 'none':
        final = df
    else:
        lo, hi = ('min', 'max') if band == 'minmax' else ('q10', 'q90')
        final = df[df['w'].between(df[lo], df[hi])]
    stats[f'band_{band}'] = len(final)

    if deep_policy == 'pass' and oos:
        deep = pd.concat(oos, ignore_index=True)
        deep = deep[deep['region'] == 'deep_intragenic']
        if not deep.empty:
            print(f"deep_intragenic=pass: appending {len(deep):,} unfiltered intragenic hits")
            final = pd.concat([final, deep], ignore_index=True)

    print("\n--- cascade ---")
    for k in ('raw', 'prefilter', 'merged', 'dedupe', 'in_scope', 'band_admitted', f'band_{band}'):
        print(f"{k:16s} {stats.get(k, 0):12,}")
    print(f"{'deep_intragenic':16s} {stats['deep_intragenic']:12,}  ({deep_policy})")
    print(f"{'beyond_flank':16s} {stats['beyond_flank']:12,}  (outside the model's field of view)")

    print("\n--- outputs ---")
    _write(final, output_dir, band)
    if write_oos and oos:
        _write(pd.concat(oos, ignore_index=True), output_dir, 'out_of_scope')

    report = {
        'geometry': geom,
        'flank_size': flank,
        'reference_gff': config['reference_gff'],
        'gff_match_rate': round(match_rate, 4),
        'filters': {'band': band, 'weight_region': wr_enabled,
                    'min_region_fraction': min_fraction, 'min_region_seqlets': min_seqlets,
                    'deep_intragenic': deep_policy, 'dedupe': do_dedupe},
        'counts': {k: int(v) for k, v in stats.items()},
        'bands_retained': int(len(ranges)),
        'bands_total': int(n_band),
        'bands_dropped': dropped_bands[['epm', 'region', 'number', 'region_fraction', 'iqr']]
                         .to_dict('records') if len(dropped_bands) else [],
    }
    with open(os.path.join(output_dir, 'annotation_report.json'), 'w') as f:
        json.dump(report, f, indent=2, default=float)
    print("  annotation_report.json")
    print("\nAnnotation step successfully completed.")
